version: '3.9'
# Frontend and node client development orchestration
name: robosats-frontend
services:
  frontend:
    build: ./
    container_name: dev-frontend
    volumes:
      - ./:/usr/src/frontend
      - ../web:/usr/src/web

  nginx:
    build: ../web
    container_name: dev-nginx
    restart: always
    volumes:
      - ../web:/usr/src/web
      - ./static/frontend:/usr/src/web/static/frontend
      - ../web/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8888:80
