import React, { Component } from 'react';
import SvgIcon from '@mui/material/SvgIcon';
import SwapCallsIcon from '@mui/icons-material/SwapCalls';

export default function getFlags(code){
    if(code == 'AUD') return '🇦🇺';
    if(code == 'ARS') return '🇦🇷';
    if(code == 'BRL') return '🇧🇷';
    if(code == 'CAD') return '🇨🇦';
    if(code == 'CHF') return '🇨🇭';
    if(code == 'CLP') return '🇨🇱';
    if(code == 'CNY') return '🇨🇳';
    if(code == 'EUR') return '🇪🇺';
    if(code == 'HRK') return '🇨🇷';
    if(code == 'CZK') return '🇨🇿';
    if(code == 'DKK') return '🇩🇰';
    if(code == 'GBP') return '🇬🇧';
    if(code == 'HKD') return '🇭🇰';
    if(code == 'HUF') return '🇭🇺';
    if(code == 'INR') return '🇮🇳';
    if(code == 'ISK') return '🇮🇸';
    if(code == 'JPY') return '🇯🇵';
    if(code == 'KRW') return '🇰🇷';
    if(code == 'MXN') return '🇲🇽';
    if(code == 'NOK') return '🇳🇴';
    if(code == 'NZD') return '🇳🇿';
    if(code == 'PLN') return '🇵🇱';
    if(code == 'RON') return '🇷🇴';
    if(code == 'RUB') return '🇷🇺';
    if(code == 'SEK') return '🇸🇪';
    if(code == 'SGD') return '🇸🇬';
    if(code == 'VES') return '🇻🇪';
    if(code == 'TRY') return '🇹🇷';
    if(code == 'USD') return '🇺🇸';
    if(code == 'ZAR') return '🇿🇦';
    if(code == 'COP') return '🇨🇴';
    if(code == 'PEN') return '🇵🇪';
    if(code == 'UYU') return '🇺🇾';
    if(code == 'PYG') return '🇵🇾';
    if(code == 'BOB') return '🇧🇴';
    if(code == 'IDR') return '🇮🇩';
    if(code == 'ANG') return '🇧🇶';
    if(code == 'CRC') return '🇨🇷';
    if(code == 'CUP') return '🇨🇺';
    if(code == 'DOP') return '🇩🇴';
    if(code == 'GHS') return '🇬🇭';
    if(code == 'GTQ') return '🇬🇹';
    if(code == 'ILS') return '🇮🇱';
    if(code == 'JMD') return '🇯🇲';
    if(code == 'KES') return '🇰🇪';
    if(code == 'KZT') return '🇰🇿';
    if(code == 'MYR') return '🇲🇲';
    if(code == 'NAD') return '🇳🇦';
    if(code == 'NGN') return '🇳🇬';
    if(code == 'AZN') return '🇦🇿';
    if(code == 'PAB') return '🇵🇦';
    if(code == 'PHP') return '🇵🇭';
    if(code == 'PKR') return '🇵🇰';
    if(code == 'QAR') return '🇶🇦';
    if(code == 'SAR') return '🇸🇦';
    if(code == 'THB') return '🇹🇭';
    if(code == 'TTD') return '🇹🇹';
    if(code == 'VND') return '🇻🇳';
    if(code == 'XOF') return '🇸🇳';
    if(code == 'TWD') return '🇹🇼';
    if(code == 'XAU') return '🟨';
    if(code == 'BTC') return <SwapCallsIcon color="primary"/>;
    return '🏳';
};
