# Generated by Django 3.2.18 on 2023-04-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="bondless_taker",
        ),
        migrations.AddField(
            model_name="order",
            name="reverted_fiat_sent",
            field=models.BooleanField(default=False),
        ),
    ]
