# Generated by Django 3.2.18 on 2023-04-30 21:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0002_auto_20230427_2023"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profile",
            new_name="Robot",
        ),
    ]
