# Generated by Django 4.2 on 2023-05-05 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_rename_profile_robot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="robot",
            name="is_referred",
        ),
        migrations.RemoveField(
            model_name="robot",
            name="pending_rewards",
        ),
        migrations.RemoveField(
            model_name="robot",
            name="referral_code",
        ),
        migrations.RemoveField(
            model_name="robot",
            name="referred_by",
        ),
    ]
