# Generated by Django 4.2 on 2023-05-05 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_robot_is_referred_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="robot",
            name="avg_rating",
        ),
        migrations.RemoveField(
            model_name="robot",
            name="latest_ratings",
        ),
        migrations.RemoveField(
            model_name="robot",
            name="total_ratings",
        ),
    ]
