# Generated by Django 4.2 on 2023-05-08 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_remove_robot_avg_rating_remove_robot_latest_ratings_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="maker_last_seen",
        ),
        migrations.RemoveField(
            model_name="order",
            name="taker_last_seen",
        ),
        migrations.AddField(
            model_name="order",
            name="proceeds",
            field=models.PositiveBigIntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
