# Generated by Django 4.2.1 on 2023-05-16 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_squashed_0036_remove_order_maker_last_seen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lnpayment",
            name="order_donated",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_donated",
                to="api.order",
            ),
        ),
        migrations.AlterField(
            model_name="lnpayment",
            name="concept",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Maker bond"),
                    (1, "Taker bond"),
                    (2, "Trade escrow"),
                    (3, "Payment to buyer"),
                    (4, "Withdraw rewards"),
                    (5, "Devfund donation"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="lnpayment",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Regular invoice"), (1, "hold invoice"), (2, "Keysend")],
                default=1,
            ),
        ),
    ]
