# Generated by Django 4.2.2 on 2023-07-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0039_alter_currency_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="robot",
            name="hash_id",
            field=models.CharField(
                blank=True, default=None, max_length=64, null=True, unique=True
            ),
        ),
    ]
