# Generated by Django 4.2.3 on 2023-08-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0040_robot_hash_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="logs",
            field=models.TextField(
                blank=True, default=None, editable=False, max_length=80000, null=True
            ),
        ),
    ]
