# Generated by Django 4.2.4 on 2023-09-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0041_order_logs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="logs",
            field=models.TextField(
                blank=True,
                default="<thead><tr><b><th>Timestamp</th><th>Level</th><th>Event</th></b></tr></thead>",
                editable=False,
                max_length=80000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="robot",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="static/assets/avatars/unknown_avatar.webp",
                upload_to="",
                verbose_name="Avatar",
            ),
        ),
    ]
