# Generated by Django 4.2.5 on 2023-10-03 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0042_alter_order_logs_alter_robot_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="latitude",
            field=models.DecimalField(
                decimal_places=6,
                max_digits=8,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="longitude",
            field=models.DecimalField(
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="bond_size",
            field=models.DecimalField(
                decimal_places=2,
                default=3.0,
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(15.0),
                ],
            ),
        ),
    ]
