# Generated by Django 4.2.6 on 2023-10-11 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0043_order_latitude_order_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="markettick",
            name="fee",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="onchainpayment",
            name="num_satoshis",
            field=models.PositiveBigIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(7500000.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="onchainpayment",
            name="sent_satoshis",
            field=models.PositiveBigIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(7500000.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="onchainpayment",
            name="swap_fee_rate",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
    ]
