# Generated by Django 5.0.6 on 2024-07-01 12:03

import api.models.order
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.UUIDField(default=api.models.order.custom_uuid, editable=False),
        ),
    ]
