# Generated by Django 5.1.9 on 2025-06-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_currency_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='password',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
