# Generated by Django 5.1.9 on 2025-07-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_order_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=240, null=True),
        ),
    ]
