# Generated by Django 5.1.15 on 2026-01-23 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='auto_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='price_limit',
            field=models.DecimalField(blank=True, decimal_places=8, default=None, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='escrow_duration',
            field=models.PositiveBigIntegerField(default=10799, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(36000)]),
        ),
    ]
