# Generated by Django 5.2.17 on 2026-08-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_robot_webhook_enabled_alter_order_escrow_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lnpayment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Generated'), (1, 'Locked'), (2, 'Settled'), (3, 'Returned'), (4, 'Cancelled'), (5, 'Expired'), (6, 'Valid'), (7, 'In flight'), (8, 'Succeeded'), (9, 'Routing failed'), (10, 'Queued')], default=0),
        ),
    ]
