# Generated by Django 5.1.15 on 2026-02-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_add_price_limit_fields'),
        ('api', '0057_robot_webhook_enabled_alter_order_escrow_duration'),
    ]

    operations = [
    ]
