# Generated by Django 5.2.17 on 2026-10-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "api",
            "0059_merge_0058_alter_order_logs_0058_lnpayment_concept_community_donation",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lnpayment",
            name="fee",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="lnpayment",
            name="routing_budget_sats",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
