export const paymentMethods = [
    {name: "Revolut",icon:'revolut'},
    {name: "CashApp",icon:'cashapp'},
    {name: "Zelle",icon:'zelle'},
    {name: "Strike",icon:'strike'},
    {name: "WeChat Pay", icon: 'wechatpay'},
    {name: "Rebellion",icon:'rebellion'},
    {name: "Instant SEPA", icon:'sepa'},
    {name: "Interac e-Transfer",icon:'interac'},
    {name: "Wise",icon:'wise'},
    {name: "Venmo",icon:'venmo'},
    {name: "Faster Payments",icon:'faster'},
    {name: "Paypal",icon:'paypal'},
    {name: "LINE Pay",icon:'linepay'},
    {name: "PromptPay",icon:'promptpay'},
    {name: "Bizum",icon:'bizum'},
    {name: "N26",icon:'n26'},
    {name: "Amazon GiftCard",icon:'amazon'},
    {name: "Amazon USA GiftCard",icon:'amazon'},
    {name: "Amazon DE GiftCard",icon:'amazon'},
    {name: "Amazon AU GiftCard",icon:'amazon'},
    {name: "Amazon SA GiftCard",icon:'amazon'},
    {name: "Amazon ES GiftCard",icon:'amazon'},
    {name: "Amazon CA GiftCard",icon:'amazon'},
    {name: "Amazon CN GiftCard",icon:'amazon'},
    {name: "Amazon EG GiftCard",icon:'amazon'},
    {name: "Amazon AE GiftCard",icon:'amazon'},
    {name: "Amazon FR GiftCard",icon:'amazon'},
    {name: "Amazon NL GiftCard",icon:'amazon'},
    {name: "Amazon IN GiftCard",icon:'amazon'},
    {name: "Amazon IT GiftCard",icon:'amazon'},
    {name: "Amazon JP GiftCard",icon:'amazon'},
    {name: "Amazon MX GiftCard",icon:'amazon'},
    {name: "Amazon PL GiftCard",icon:'amazon'},
    {name: "Amazon UK GiftCard",icon:'amazon'},
    {name: "Amazon SE GiftCard",icon:'amazon'},
    {name: "Amazon SG GiftCard",icon:'amazon'},
    {name: "Amazon TR GiftCard",icon:'amazon'},
    {name: "AliPay", icon: 'alipay'},
    {name: "Bancolombia",icon:'bancolombia'},
    {name: "SPEI",icon:'spei'},
    {name: "PIX",icon:'pix'},
    {name: "HalCash",icon:'halcash'},
    {name: "Vivid",icon:'vivid'},
    {name: "Google Play Gift Code",icon:'googleplay'},
    {name: "Nequi",icon:'nequi'},
    {name: "ShakePay",icon:'shakepay'},
    {name: "DaviPlata",icon:'daviplata'},
    {name: "CoDi",icon:'codi'},
    {name: "TaiwanPay",icon:'taiwanpay'},
    {name: "MaiCoin",icon:'maicoin'},
    {name: "MercadoPago",icon:'mercadopago'},
    {name: "Monero",icon:'monero'},
    {name: "USDT",icon:'usdt'},
    {name: "Airtel Money",icon:'airtel'},
    {name: "MTN Money",icon:'mtn'},
    {name: "M-Pesa",icon:'mpesa'},
    {name: "MoMo",icon:'momo'},
    {name: "Tigo Pesa",icon:'tigopesa'},
    {name: "Cash F2F",icon:'cash'},
  ];
  
export const swapDestinations = [
    {name: "On-Chain BTC",icon:'onchain'},
    {name: "RBTC",icon:'rbtc'},
    {name: "LBTC",icon:'lbtc'},
    {name: "WBTC",icon:'wbtc'},
  ];