version: '3.9'
services:
  jekyll:
    image: jekyll/jekyll:4.0
    container_name: pages
    restart: always
    volumes:
      - .:/usr/src/docs
    command: bash -c "cd /usr/src/docs/
            && bundle install 
            && bundle exec jekyll serve --force_polling -H 0.0.0.0 -P 4000"
    ports:
      - 4000:4000