# Generated by Django 3.2.18 on 2023-04-27 20:21

import control.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountingDay",
            fields=[
                ("day", models.DateTimeField(primary_key=True, serialize=False)),
                (
                    "contracted",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                ("num_contracts", models.BigIntegerField(default=0)),
                (
                    "net_settled",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "net_paid",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "net_balance",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "inflow",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "outflow",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "routing_fees",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "mining_fees",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "cashflow",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "outstanding_earned_rewards",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "outstanding_pending_disputes",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "lifetime_rewards_claimed",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "earned_rewards",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "disputes",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "rewards_claimed",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BalanceLog",
            fields=[
                (
                    "time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total",
                    models.PositiveBigIntegerField(
                        default=control.models.BalanceLog.get_total
                    ),
                ),
                (
                    "onchain_fraction",
                    models.DecimalField(
                        decimal_places=5,
                        default=control.models.BalanceLog.get_frac,
                        max_digits=6,
                    ),
                ),
                (
                    "onchain_total",
                    models.PositiveBigIntegerField(
                        default=control.models.BalanceLog.get_oc_total
                    ),
                ),
                (
                    "onchain_confirmed",
                    models.PositiveBigIntegerField(
                        default=control.models.BalanceLog.get_oc_conf
                    ),
                ),
                (
                    "onchain_unconfirmed",
                    models.PositiveBigIntegerField(
                        default=control.models.BalanceLog.get_oc_unconf
                    ),
                ),
                (
                    "ln_local",
                    models.PositiveBigIntegerField(
                        default=control.models.BalanceLog.get_ln_local
                    ),
                ),
                (
                    "ln_remote",
                    models.PositiveBigIntegerField(
                        default=control.models.BalanceLog.get_ln_remote
                    ),
                ),
                (
                    "ln_local_unsettled",
                    models.PositiveBigIntegerField(
                        default=control.models.BalanceLog.get_ln_local_unsettled
                    ),
                ),
                (
                    "ln_remote_unsettled",
                    models.PositiveBigIntegerField(
                        default=control.models.BalanceLog.get_ln_remote_unsettled
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
