# Generated by Django 4.2.7 on 2023-11-30 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("control", "0002_auto_20220619_0535"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="balancelog",
            options={"get_latest_by": "time"},
        ),
    ]
