name: "Test: Coordinator"

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ "main" ]
    paths: ["api", "chat", "control", "robosats"]
  pull_request:
    branches: [ "main" ]
    paths: ["api", "chat", "control", "robosats"]

# concurrency:
#   group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
#   cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEVELOPMENT: 1
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11"]

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
    - name: 'Set up Python ${{ matrix.python-version }}'
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: 'Install Python Dependencies'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 'Install LND gRPC Dependencies'
      run: bash ./scripts/generate_grpc.sh
    - name: 'Create .env File'
      run: |
        mv .env-sample .env
    - name:  'Tests'
      run: |
        python manage.py test