name: RoboSats Client Node App Image CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: ["frontend", "nodeapp"]
  pull_request:
    branches: [ "main" ]
    paths: ["frontend", "nodeapp"]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  push_to_registry:
    name: 'Push Docker image to Docker Hub'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: 'Download main.js Artifact'
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: frontend-build.yml
        workflow_conclusion: success
        name: main-js
        path: frontend/static/frontend/
        
    - name: 'Log in to Docker Hub'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 'Extract metadata (tags, labels) for Docker'
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: recksato/robosats-client
        tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

    - name: 'Get Commit Hash'
      id: commit
      uses: pr-mpt/actions-commit-hash@v1

    - name: 'Save Commit Long Hash to TXT File'
      run: |
        echo ${{ steps.commit.outputs.long }}>"commit_sha.txt"

    - name: 'Set up QEMU'
      uses: docker/setup-qemu-action@v2
    
    - name: 'Set up Docker Buildx'
      uses: docker/setup-buildx-action@v2
    
    - name: 'Build and push Docker image'
      uses: docker/build-push-action@v3
      with:
        context: ./nodeapp
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          recksato/robosats-client:${{ steps.commit.outputs.short }}
          recksato/robosats-client:latest
        labels: ${{ steps.meta.outputs.labels }}

